### ISSUE TITLE
using reset_token route crashes server

### ISSUE THREAD

**Issue by idkjs** [simplecode-io/simple-api#3] opened 2019-10-03 20:59 UTC
Hi @Owen, 

Looks like running the `reset_password` route crashes the app with this error:

```s
Unhandled rejection Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:467:11)
    at ServerResponse.header (/Users/prisc_000/Downloads/simple-api-master/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/Users/prisc_000/Downloads/simple-api-master/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/prisc_000/Downloads/simple-api-master/node_modules/express/lib/response.js:267:15)
    at /Users/prisc_000/Downloads/simple-api-master/api/routes/users.js:324:33
    at tryCatcher (/Users/prisc_000/Downloads/simple-api-master/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/prisc_000/Downloads/simple-api-master/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/prisc_000/Downloads/simple-api-master/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/prisc_000/Downloads/simple-api-master/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/prisc_000/Downloads/simple-api-master/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/Users/prisc_000/Downloads/simple-api-master/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/prisc_000/Downloads/simple-api-master/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/prisc_000/Downloads/simple-api-master/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/prisc_000/Downloads/simple-api-master/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:126:23)
``` 

This is happening on the master repo after running `npm install` add configuring postgres and ses.  I can't get my head around what is happening though I reread this stackovflow [post](https://stackoverflow.com/questions/7042340/error-cant-set-headers-after-they-are-sent-to-the-client) a few times. Is this expected?

Thank you.

Originally posted here but not to many responses there. https://community.simplecode.io/t/create-a-rest-api-part-7-forgot-reset-password-routes/28/2?u=idkjs

**Comment by simplecode-io** [comment] 2019-10-03 22:09
Hey @idkjs, Thanks for pointing this out. I found the issue and posted a response over at the community forums. I'll have it fixed in the tutorial and this repo in a minute. Let us know if you need any more help with the tutorials. :+1:

**Closed by simplecode-io** 2019-10-03 22:09 UTC

**Comment by idkjs** [comment] 2019-10-03 22:15
I think it was a faulty if/else statement? Thanks so much for the rapid response. Keep up the hustle, sir!

**Comment by simplecode-io** [comment] 2019-10-03 22:36
Not a problem! This problem was having `sendEmail.Email(to, subject, content);` after `res.json("Password successfully changed for " + user[0] + "!");`

You can't run anything after res.json. Whoops. So if you swap the res.json with the sendEmail line, the problem is fixed. All the best in your developer career!
